export const dateFormat = [
  "YYYY-MM-DD",
  "YYYY-MM-DD HH:mm:ss",
  "YYYY-MM-DDTHH:mm:ssZ",
  "YYYY-MM-DDTHH:mm:ss.SSSZ",
  "MM/DD/YYYY",
  "MM/DD/YYYY HH:mm:ss",
  "MM/DD/YYYY HH:mm:ss.SSS",
  "DD/MM/YYYY",
  "DD/MM/YYYY HH:mm:ss",
  "DD/MM/YYYY HH:mm:ss.SSS",
  "YYYY/MM/DD",
  "YYYY/MM/DD HH:mm:ss",
  "YYYY/MM/DD HH:mm:ss.SSS",
  "MM-DD-YYYY",
  "MM-DD-YYYY HH:mm:ss",
  "MM-DD-YYYY HH:mm:ss.SSS",
  "DD-MM-YYYY",
  "DD-MM-YYYY HH:mm:ss",
  "DD-MM-YYYY HH:mm:ss.SSS",
  "YYYY.MMM.DD",
  "YYYY.MMM.DD HH:mm:ss",
  "YYYY.MMM.DD HH:mm:ss.SSS",
  "MMM DD, YYYY",
  "MMM DD, YYYY HH:mm:ss",
  "MMM DD, YYYY HH:mm:ss.SSS",
  "DD MMM, YYYY",
  "DD MMM, YYYY HH:mm:ss",
  "DD MMM, YYYY HH:mm:ss.SSS",
];
