export const mobile_country = [
  { country: "Afghanistan", mcc: "+93" },
  { country: "Albania", mcc: "+355" },
  { country: "Algeria", mcc: "+213" },
  { country: "American Samoa", mcc: "+1-684" },
  { country: "Andorra", mcc: "+376" },
  { country: "Angola", mcc: "+244" },
  { country: "Anguilla", mcc: "+1-264" },
  { country: "Antigua and Barbuda", mcc: "+1-268" },
  { country: "Argentina", mcc: "+54" },
  { country: "Armenia", mcc: "+374" },
  { country: "Aruba", mcc: "+297" },
  { country: "Australia", mcc: "+61" },
  { country: "Austria", mcc: "+43" },
  { country: "Azerbaijan", mcc: "+994" },
  { country: "Bahamas", mcc: "+1-242" },
  { country: "Bahrain", mcc: "+973" },
  { country: "Bangladesh", mcc: "+880" },
  { country: "Barbados", mcc: "+1-246" },
  { country: "Belarus", mcc: "+375" },
  { country: "Belgium", mcc: "+32" },
  { country: "Belize", mcc: "+501" },
  { country: "Benin", mcc: "+229" },
  { country: "Bermuda", mcc: "+1-441" },
  { country: "Bhutan", mcc: "+975" },
  { country: "Bolivia", mcc: "+591" },
  { country: "Bosnia and Herzegovina", mcc: "+387" },
  { country: "Botswana", mcc: "+267" },
  { country: "Brazil", mcc: "+55" },
  { country: "British Indian Ocean Territory", mcc: "+246" },
  { country: "British Virgin Islands", mcc: "+1-284" },
  { country: "Brunei", mcc: "+673" },
  { country: "Bulgaria", mcc: "+359" },
  { country: "Burkina Faso", mcc: "+226" },
  { country: "Burundi", mcc: "+257" },
  { country: "Cambodia", mcc: "+855" },
  { country: "Cameroon", mcc: "+237" },
  { country: "Canada", mcc: "+1" },
  { country: "Cape Verde", mcc: "+238" },
  { country: "Caribbean Netherlands", mcc: "+599" },
  { country: "Cayman Islands", mcc: "+1-345" },
  { country: "Central African Republic", mcc: "+236" },
  { country: "Chad", mcc: "+235" },
  { country: "Chile", mcc: "+56" },
  { country: "China", mcc: "+86" },
  { country: "Christmas Island", mcc: "+61" },
  { country: "Cocos (Keeling) Islands", mcc: "+61" },
  { country: "Colombia", mcc: "+57" },
  { country: "Comoros", mcc: "+269" },
  { country: "Congo (Brazzaville)", mcc: "+242" },
  { country: "Congo (Kinshasa)", mcc: "+243" },
  { country: "Cook Islands", mcc: "+682" },
  { country: "Costa Rica", mcc: "+506" },
  { country: "Côte d'Ivoire", mcc: "+225" },
  { country: "Croatia", mcc: "+385" },
  { country: "Cuba", mcc: "+53" },
  { country: "Curaçao", mcc: "+599" },
  { country: "Cyprus", mcc: "+357" },
  { country: "Czech Republic", mcc: "+420" },
  { country: "Denmark", mcc: "+45" },
  { country: "Djibouti", mcc: "+253" },
  { country: "Dominica", mcc: "+1-767" },
  { country: "Dominican Republic", mcc: "+1-809, +1-829, +1-849" },
  { country: "East Timor", mcc: "+670" },
  { country: "Ecuador", mcc: "+593" },
  { country: "Egypt", mcc: "+20" },
  { country: "El Salvador", mcc: "+503" },
  { country: "Equatorial Guinea", mcc: "+240" },
  { country: "Eritrea", mcc: "+291" },
  { country: "Estonia", mcc: "+372" },
  { country: "Eswatini", mcc: "+268" },
  { country: "Ethiopia", mcc: "+251" },
  { country: "Falkland Islands", mcc: "+500" },
  { country: "Faroe Islands", mcc: "+298" },
  { country: "Fiji", mcc: "+679" },
  { country: "Finland", mcc: "+358" },
  { country: "France", mcc: "+33" },
  { country: "French Guiana", mcc: "+594" },
  { country: "French Polynesia", mcc: "+689" },
  { country: "Gabon", mcc: "+241" },
  { country: "Gambia", mcc: "+220" },
  { country: "Georgia", mcc: "+995" },
  { country: "Germany", mcc: "+49" },
  { country: "Ghana", mcc: "+233" },
  { country: "Gibraltar", mcc: "+350" },
  { country: "Greece", mcc: "+30" },
  { country: "Greenland", mcc: "+299" },
  { country: "Grenada", mcc: "+1-473" },
  { country: "Guadeloupe", mcc: "+590" },
  { country: "Guam", mcc: "+1-671" },
  { country: "Guatemala", mcc: "+502" },
  { country: "Guernsey", mcc: "+44-1481" },
  { country: "Guinea", mcc: "+224" },
  { country: "Guinea-Bissau", mcc: "+245" },
  { country: "Guyana", mcc: "+592" },
  { country: "Haiti", mcc: "+509" },
  { country: "Honduras", mcc: "+504" },
  { country: "Hong Kong SAR China", mcc: "+852" },
  { country: "Hungary", mcc: "+36" },
  { country: "Iceland", mcc: "+354" },
  { country: "India", mcc: "+91" },
  { country: "Indonesia", mcc: "+62" },
  { country: "Iran", mcc: "+98" },
  { country: "Iraq", mcc: "+964" },
  { country: "Ireland", mcc: "+353" },
  { country: "Isle of Man", mcc: "+44-1624" },
  { country: "Israel", mcc: "+972" },
  { country: "Italy", mcc: "+39" },
  { country: "Jamaica", mcc: "+1-876" },
  { country: "Japan", mcc: "+81" },
  { country: "Jersey", mcc: "+44-1534" },
  { country: "Jordan", mcc: "+962" },
  { country: "Kazakhstan", mcc: "+7" },
  { country: "Kenya", mcc: "+254" },
  { country: "Kiribati", mcc: "+686" },
  { country: "Kosovo", mcc: "+383" },
  { country: "Kuwait", mcc: "+965" },
  { country: "Kyrgyzstan", mcc: "+996" },
  { country: "Laos", mcc: "+856" },
  { country: "Latvia", mcc: "+371" },
  { country: "Lebanon", mcc: "+961" },
  { country: "Lesotho", mcc: "+266" },
  { country: "Liberia", mcc: "+231" },
  { country: "Libya", mcc: "+218" },
  { country: "Liechtenstein", mcc: "+423" },
  { country: "Lithuania", mcc: "+370" },
  { country: "Luxembourg", mcc: "+352" },
  { country: "Macau SAR China", mcc: "+853" },
  { country: "Madagascar", mcc: "+261" },
  { country: "Malawi", mcc: "+265" },
  { country: "Malaysia", mcc: "+60" },
  { country: "Maldives", mcc: "+960" },
  { country: "Mali", mcc: "+223" },
  { country: "Malta", mcc: "+356" },
  { country: "Marshall Islands", mcc: "+692" },
  { country: "Martinique", mcc: "+596" },
  { country: "Mauritania", mcc: "+222" },
  { country: "Mauritius", mcc: "+230" },
  { country: "Mayotte", mcc: "+262" },
  { country: "Mexico", mcc: "+52" },
  { country: "Micronesia", mcc: "+691" },
  { country: "Moldova", mcc: "+373" },
  { country: "Monaco", mcc: "+377" },
  { country: "Mongolia", mcc: "+976" },
  { country: "Montenegro", mcc: "+382" },
  { country: "Montserrat", mcc: "+1-664" },
  { country: "Morocco", mcc: "+212" },
  { country: "Mozambique", mcc: "+258" },
  { country: "Myanmar (Burma)", mcc: "+95" },
  { country: "Namibia", mcc: "+264" },
  { country: "Nauru", mcc: "+674" },
  { country: "Nepal", mcc: "+977" },
  { country: "Netherlands", mcc: "+31" },
  { country: "New Caledonia", mcc: "+687" },
  { country: "New Zealand", mcc: "+64" },
  { country: "Nicaragua", mcc: "+505" },
  { country: "Niger", mcc: "+227" },
  { country: "Nigeria", mcc: "+234" },
  { country: "Niue", mcc: "+683" },
  { country: "Norfolk Island", mcc: "+672" },
  { country: "North Korea", mcc: "+850" },
  { country: "North Macedonia", mcc: "+389" },
  { country: "Northern Mariana Islands", mcc: "+1-670" },
  { country: "Norway", mcc: "+47" },
  { country: "Oman", mcc: "+968" },
  { country: "Pakistan", mcc: "+92" },
  { country: "Palau", mcc: "+680" },
  { country: "Palestinian Territories", mcc: "+970" },
  { country: "Panama", mcc: "+507" },
  { country: "Papua New Guinea", mcc: "+675" },
  { country: "Paraguay", mcc: "+595" },
  { country: "Peru", mcc: "+51" },
  { country: "Philippines", mcc: "+63" },
  { country: "Poland", mcc: "+48" },
  { country: "Portugal", mcc: "+351" },
  { country: "Puerto Rico", mcc: "+1-787, +1-939" },
  { country: "Qatar", mcc: "+974" },
  { country: "Réunion", mcc: "+262" },
  { country: "Romania", mcc: "+40" },
  { country: "Russia", mcc: "+7" },
  { country: "Rwanda", mcc: "+250" },
  { country: "Saint Barthélemy", mcc: "+590" },
  { country: "Saint Helena", mcc: "+290" },
  { country: "Saint Kitts and Nevis", mcc: "+1-869" },
  { country: "Saint Lucia", mcc: "+1-758" },
  { country: "Saint Martin", mcc: "+590" },
  { country: "Saint Pierre and Miquelon", mcc: "+508" },
  { country: "Saint Vincent and the Grenadines", mcc: "+1-784" },
  { country: "Samoa", mcc: "+685" },
  { country: "San Marino", mcc: "+378" },
  { country: "São Tomé and Príncipe", mcc: "+239" },
  { country: "Saudi Arabia", mcc: "+966" },
  { country: "Senegal", mcc: "+221" },
  { country: "Serbia", mcc: "+381" },
  { country: "Seychelles", mcc: "+248" },
  { country: "Sierra Leone", mcc: "+232" },
  { country: "Singapore", mcc: "+65" },
  { country: "Sint Maarten", mcc: "+1-721" },
  { country: "Slovakia", mcc: "+421" },
  { country: "Slovenia", mcc: "+386" },
  { country: "Solomon Islands", mcc: "+677" },
  { country: "Somalia", mcc: "+252" },
  { country: "South Africa", mcc: "+27" },
  { country: "South Korea", mcc: "+82" },
  { country: "South Sudan", mcc: "+211" },
  { country: "Spain", mcc: "+34" },
  { country: "Sri Lanka", mcc: "+94" },
  { country: "Sudan", mcc: "+249" },
  { country: "Suriname", mcc: "+597" },
  { country: "Sweden", mcc: "+46" },
  { country: "Switzerland", mcc: "+41" },
  { country: "Syria", mcc: "+963" },
  { country: "Taiwan", mcc: "+886" },
  { country: "Tajikistan", mcc: "+992" },
  { country: "Tanzania", mcc: "+255" },
  { country: "Thailand", mcc: "+66" },
  { country: "Togo", mcc: "+228" },
  { country: "Tokelau", mcc: "+690" },
  { country: "Tonga", mcc: "+676" },
  { country: "Trinidad and Tobago", mcc: "+1-868" },
  { country: "Tunisia", mcc: "+216" },
  { country: "Turkey", mcc: "+90" },
  { country: "Turkmenistan", mcc: "+993" },
  { country: "Turks and Caicos Islands", mcc: "+1-649" },
  { country: "Tuvalu", mcc: "+688" },
  { country: "U.S. Virgin Islands", mcc: "+1-340" },
  { country: "Uganda", mcc: "+256" },
  { country: "Ukraine", mcc: "+380" },
  { country: "United Arab Emirates", mcc: "+971" },
  { country: "United Kingdom", mcc: "+44" },
  { country: "United States", mcc: "+1" },
  { country: "Uruguay", mcc: "+598" },
  { country: "Uzbekistan", mcc: "+998" },
  { country: "Vanuatu", mcc: "+678" },
  { country: "Vatican City", mcc: "+379" },
  { country: "Venezuela", mcc: "+58" },
  { country: "Vietnam", mcc: "+84" },
  { country: "Wallis and Futuna", mcc: "+681" },
  { country: "Yemen", mcc: "+967" },
  { country: "Zambia", mcc: "+260" },
  { country: "Zimbabwe", mcc: "+263" },
];
